import Link from 'next/link';
import './globals.css';
import LoginBtn from './LoginBtn';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import LogoutBtn from './LogoutBtn';
import SignUp from './SignUp';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  let data = await getServerSession(authOptions);
  console.log(data);
  return (
    <html lang='en'>
      <body>
        <div className='navbar'>
          <Link href='/' className='logo'>
            Appleforum
          </Link>
          <Link href='/write'>Write</Link>
          <Link href='/list'>List</Link>

          {data ? (
            <span>
              {data.user.name} <LogoutBtn />
            </span>
          ) : (
            <span>
              <LoginBtn />
              <SignUp />
            </span>
          )}
        </div>
        {children}
      </body>
    </html>
  );
}
