import './globals.css';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <div className='navbar'>
          <Link href='/'>home</Link>
          <Link href='/list'>list페이지</Link>
        </div>
        <p>현대카드 무이자 이벤트 중</p>
        {children}
      </body>
    </html>
  );
}
